In [4]:
import sys
from pathlib import Path

print("Current working directory:")
print(Path.cwd())

Current working directory:
d:\simplexid_experiment_scaffold\simplexid_experiment\notebooks

In [6]:
import sys
from pathlib import Path

ROOT = Path.cwd().parent

sys.path.insert(
    0,
    str(ROOT / "src")
)

import pandas as pd

from simplexid.data import (
    load_terma,
    load_hoasa,
    prepare_terma,
    prepare_hoasa,
)

Prepare Terma Dataset

In [7]:
terma_raw = load_terma()

terma_raw

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Using the latest cached version of the dataset since indonlp/indonlu couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'terma' at C:\Users\USER\.cache\huggingface\datasets\indonlp___indonlu\terma\1.0.0\4f6bd3985d38bfa901609cc151c052caaa4612322688a67e5aec267a78e930a0 (last modified on Sun Aug  9 21:32:34 2026).

DatasetDict({
    train: Dataset({
        features: ['tokens', 'seq_label'],
        num_rows: 3000
    })
    validation: Dataset({
        features: ['tokens', 'seq_label'],
        num_rows: 1000
    })
    test: Dataset({
        features: ['tokens', 'seq_label'],
        num_rows: 1000
    })
})

In [8]:
print(
    terma_raw["train"].features
)

print(
    terma_raw["train"][0]
)

{'tokens': List(Value('string')), 'seq_label': List(ClassLabel(names=['I-SENTIMENT', 'O', 'I-ASPECT', 'B-SENTIMENT', 'B-ASPECT']))}
{'tokens': ['kamar', 'saya', 'ada', 'kendala', 'di', 'ac', 'tidak', 'berfungsi', 'optimal', '.', 'dan', 'juga', 'wifi', 'koneksi', 'kurang', 'stabil', '.'], 'seq_label': [1, 1, 1, 1, 1, 4, 3, 0, 0, 1, 1, 1, 4, 2, 3, 0, 1]}

In [9]:
terma = prepare_terma(
    terma_raw
)

terma.head()

,sentence_id,dataset,source_split,sentence,tokens,labels,aspects,opinions,n_aspects,n_opinions,labels_available
0,terma_train_00000,terma,train,kamar saya ada kendala di ac tidak berfungsi o...,"[""kamar"", ""saya"", ""ada"", ""kendala"", ""di"", ""ac""...","[""O"", ""O"", ""O"", ""O"", ""O"", ""B-ASPECT"", ""B-SENTI...","[{""start"": 5, ""end"": 5, ""text"": ""ac""}, {""start...","[{""start"": 6, ""end"": 8, ""text"": ""tidak berfung...",2.0,2.0,True
1,terma_train_00001,terma,train,tempatnya bagus . kolam renangnya bersih .,"[""tempatnya"", ""bagus"", ""."", ""kolam"", ""renangny...","[""B-ASPECT"", ""B-SENTIMENT"", ""O"", ""B-ASPECT"", ""...","[{""start"": 0, ""end"": 0, ""text"": ""tempatnya""}, ...","[{""start"": 1, ""end"": 1, ""text"": ""bagus""}, {""st...",2.0,2.0,True
2,terma_train_00002,terma,train,"oke banget , tetapi ac nya tidak bisa diatur s...","[""oke"", ""banget"", "","", ""tetapi"", ""ac"", ""nya"", ...","[""B-SENTIMENT"", ""I-SENTIMENT"", ""O"", ""O"", ""B-AS...","[{""start"": 4, ""end"": 5, ""text"": ""ac nya""}]","[{""start"": 0, ""end"": 1, ""text"": ""oke banget""},...",1.0,2.0,True
3,terma_train_00003,terma,train,pintu geser kurang rapat .,"[""pintu"", ""geser"", ""kurang"", ""rapat"", "".""]","[""B-ASPECT"", ""I-ASPECT"", ""B-SENTIMENT"", ""I-SEN...","[{""start"": 0, ""end"": 1, ""text"": ""pintu geser""}]","[{""start"": 2, ""end"": 3, ""text"": ""kurang rapat""}]",1.0,1.0,True
4,terma_train_00004,terma,train,keren . nyaman semuanya .,"[""keren"", ""."", ""nyaman"", ""semuanya"", "".""]","[""B-SENTIMENT"", ""O"", ""B-SENTIMENT"", ""B-ASPECT""...","[{""start"": 3, ""end"": 3, ""text"": ""semuanya""}]","[{""start"": 0, ""end"": 0, ""text"": ""keren""}, {""st...",1.0,2.0,True

In [10]:
terma.shape

(5000, 11)

In [11]:
terma[
    terma["labels_available"]
][
    [
        "sentence_id",
        "sentence",
        "aspects",
        "opinions",
        "n_aspects",
        "n_opinions",
    ]
].head(20)

,sentence_id,sentence,aspects,opinions,n_aspects,n_opinions
0,terma_train_00000,kamar saya ada kendala di ac tidak berfungsi o...,"[{""start"": 5, ""end"": 5, ""text"": ""ac""}, {""start...","[{""start"": 6, ""end"": 8, ""text"": ""tidak berfung...",2.0,2.0
1,terma_train_00001,tempatnya bagus . kolam renangnya bersih .,"[{""start"": 0, ""end"": 0, ""text"": ""tempatnya""}, ...","[{""start"": 1, ""end"": 1, ""text"": ""bagus""}, {""st...",2.0,2.0
2,terma_train_00002,"oke banget , tetapi ac nya tidak bisa diatur s...","[{""start"": 4, ""end"": 5, ""text"": ""ac nya""}]","[{""start"": 0, ""end"": 1, ""text"": ""oke banget""},...",1.0,2.0
3,terma_train_00003,pintu geser kurang rapat .,"[{""start"": 0, ""end"": 1, ""text"": ""pintu geser""}]","[{""start"": 2, ""end"": 3, ""text"": ""kurang rapat""}]",1.0,1.0
4,terma_train_00004,keren . nyaman semuanya .,"[{""start"": 3, ""end"": 3, ""text"": ""semuanya""}]","[{""start"": 0, ""end"": 0, ""text"": ""keren""}, {""st...",1.0,2.0
5,terma_train_00005,"tidak dapat snack . setelah di keluhan , baru ...","[{""start"": 2, ""end"": 2, ""text"": ""snack""}]","[{""start"": 0, ""end"": 1, ""text"": ""tidak dapat""}]",1.0,1.0
6,terma_train_00006,pelayanan lumayan baik .,"[{""start"": 0, ""end"": 0, ""text"": ""pelayanan""}]","[{""start"": 1, ""end"": 2, ""text"": ""lumayan baik""}]",1.0,1.0
7,terma_train_00007,overall bagus . terjangkau . kapan kapam inap ...,"[{""start"": 0, ""end"": 0, ""text"": ""overall""}]","[{""start"": 1, ""end"": 1, ""text"": ""bagus""}, {""st...",1.0,2.0
8,terma_train_00008,"pelayanan mas nya sangat baik , membantu , ram...","[{""start"": 0, ""end"": 2, ""text"": ""pelayanan mas...","[{""start"": 3, ""end"": 4, ""text"": ""sangat baik""}...",4.0,7.0
9,terma_train_00009,airyroom ini sangat mengecewakan dalam hal lay...,"[{""start"": 6, ""end"": 6, ""text"": ""layanan""}, {""...","[{""start"": 2, ""end"": 3, ""text"": ""sangat mengec...",2.0,1.0
10,terma_train_00010,agak perlu dibersihkan . kamar banyak semut .,"[{""start"": 4, ""end"": 4, ""text"": ""kamar""}]","[{""start"": 0, ""end"": 2, ""text"": ""agak perlu di...",1.0,2.0
11,terma_train_00011,pelayanan sangat buruk . mohon diperbaiki .,"[{""start"": 0, ""end"": 0, ""text"": ""pelayanan""}]","[{""start"": 1, ""end"": 2, ""text"": ""sangat buruk""...",1.0,2.0
12,terma_train_00012,pelayanan nya sangat ramah .,"[{""start"": 0, ""end"": 1, ""text"": ""pelayanan nya""}]","[{""start"": 2, ""end"": 3, ""text"": ""sangat ramah""}]",1.0,1.0
13,terma_train_00013,kamarnya oke .,"[{""start"": 0, ""end"": 0, ""text"": ""kamarnya""}]","[{""start"": 1, ""end"": 1, ""text"": ""oke""}]",1.0,1.0
14,terma_train_00014,saya sampai sanur itu sekitar pukul 20.00 wita...,"[{""start"": 16, ""end"": 16, ""text"": ""cs""}, {""sta...","[{""start"": 18, ""end"": 20, ""text"": ""tidak cukup...",2.0,2.0
15,terma_train_00015,"recomended , hotel dengan price murah tetapi f...","[{""start"": 4, ""end"": 4, ""text"": ""price""}, {""st...","[{""start"": 0, ""end"": 0, ""text"": ""recomended""},...",4.0,5.0
16,terma_train_00016,sayang wifi tidak bagus harus keluar kamar .,"[{""start"": 1, ""end"": 1, ""text"": ""wifi""}]","[{""start"": 2, ""end"": 3, ""text"": ""tidak bagus""}]",1.0,1.0
17,terma_train_00017,fasilitas lengkap . dapat snack juga dari airy...,"[{""start"": 0, ""end"": 0, ""text"": ""fasilitas""}, ...","[{""start"": 1, ""end"": 1, ""text"": ""lengkap""}, {""...",2.0,2.0
18,terma_train_00018,fasilitas parkiran agar disediakan .,[],[],0.0,0.0
19,terma_train_00019,pelayanan nya sangat bagus . kamar nya juga oke .,"[{""start"": 0, ""end"": 1, ""text"": ""pelayanan nya...","[{""start"": 2, ""end"": 3, ""text"": ""sangat bagus""...",2.0,2.0

In [12]:
terma[
    (
        terma["n_aspects"].fillna(0) > 1
    )
    |
    (
        terma["n_opinions"].fillna(0) > 1
    )
][
    [
        "sentence",
        "aspects",
        "opinions"
    ]
].head(20)

,sentence,aspects,opinions
0,kamar saya ada kendala di ac tidak berfungsi o...,"[{""start"": 5, ""end"": 5, ""text"": ""ac""}, {""start...","[{""start"": 6, ""end"": 8, ""text"": ""tidak berfung..."
1,tempatnya bagus . kolam renangnya bersih .,"[{""start"": 0, ""end"": 0, ""text"": ""tempatnya""}, ...","[{""start"": 1, ""end"": 1, ""text"": ""bagus""}, {""st..."
2,"oke banget , tetapi ac nya tidak bisa diatur s...","[{""start"": 4, ""end"": 5, ""text"": ""ac nya""}]","[{""start"": 0, ""end"": 1, ""text"": ""oke banget""},..."
4,keren . nyaman semuanya .,"[{""start"": 3, ""end"": 3, ""text"": ""semuanya""}]","[{""start"": 0, ""end"": 0, ""text"": ""keren""}, {""st..."
7,overall bagus . terjangkau . kapan kapam inap ...,"[{""start"": 0, ""end"": 0, ""text"": ""overall""}]","[{""start"": 1, ""end"": 1, ""text"": ""bagus""}, {""st..."
8,"pelayanan mas nya sangat baik , membantu , ram...","[{""start"": 0, ""end"": 2, ""text"": ""pelayanan mas...","[{""start"": 3, ""end"": 4, ""text"": ""sangat baik""}..."
9,airyroom ini sangat mengecewakan dalam hal lay...,"[{""start"": 6, ""end"": 6, ""text"": ""layanan""}, {""...","[{""start"": 2, ""end"": 3, ""text"": ""sangat mengec..."
10,agak perlu dibersihkan . kamar banyak semut .,"[{""start"": 4, ""end"": 4, ""text"": ""kamar""}]","[{""start"": 0, ""end"": 2, ""text"": ""agak perlu di..."
11,pelayanan sangat buruk . mohon diperbaiki .,"[{""start"": 0, ""end"": 0, ""text"": ""pelayanan""}]","[{""start"": 1, ""end"": 2, ""text"": ""sangat buruk""..."
14,saya sampai sanur itu sekitar pukul 20.00 wita...,"[{""start"": 16, ""end"": 16, ""text"": ""cs""}, {""sta...","[{""start"": 18, ""end"": 20, ""text"": ""tidak cukup..."
15,"recomended , hotel dengan price murah tetapi f...","[{""start"": 4, ""end"": 4, ""text"": ""price""}, {""st...","[{""start"": 0, ""end"": 0, ""text"": ""recomended""},..."
17,fasilitas lengkap . dapat snack juga dari airy...,"[{""start"": 0, ""end"": 0, ""text"": ""fasilitas""}, ...","[{""start"": 1, ""end"": 1, ""text"": ""lengkap""}, {""..."
19,pelayanan nya sangat bagus . kamar nya juga oke .,"[{""start"": 0, ""end"": 1, ""text"": ""pelayanan nya...","[{""start"": 2, ""end"": 3, ""text"": ""sangat bagus""..."
20,"kamar cukup luas , interior menarik dan unik s...","[{""start"": 0, ""end"": 0, ""text"": ""kamar""}, {""st...","[{""start"": 1, ""end"": 2, ""text"": ""cukup luas""},..."
21,lokasi strategis harga terjangkau bangunan lam...,"[{""start"": 0, ""end"": 0, ""text"": ""lokasi""}, {""s...","[{""start"": 1, ""end"": 1, ""text"": ""strategis""}, ..."
22,"kebersihan selimut , sarung bantal , handuk ku...","[{""start"": 0, ""end"": 1, ""text"": ""kebersihan se...","[{""start"": 7, ""end"": 7, ""text"": ""kurang""}, {""s..."
23,nyaman banget kamarnya . bersiih . dan buat be...,"[{""start"": 2, ""end"": 2, ""text"": ""kamarnya""}]","[{""start"": 0, ""end"": 1, ""text"": ""nyaman banget..."
26,tempat nya nyaman dan harga nya pun terjangkau...,"[{""start"": 0, ""end"": 1, ""text"": ""tempat nya""},...","[{""start"": 2, ""end"": 2, ""text"": ""nyaman""}, {""s..."
27,kamar oke . ac kurang dingin . lampu kamar man...,"[{""start"": 0, ""end"": 0, ""text"": ""kamar""}, {""st...","[{""start"": 1, ""end"": 1, ""text"": ""oke""}, {""star..."
28,"kamar luas dan kedap , bersih makanan enak . d...","[{""start"": 0, ""end"": 0, ""text"": ""kamar""}, {""st...","[{""start"": 1, ""end"": 1, ""text"": ""luas""}, {""sta..."

In [13]:
labeled_terma = terma[
    terma["labels_available"]
]

print(
    "Labeled sentences:",
    len(labeled_terma)
)

print(
    "1 aspect + 1 opinion:",
    (
        (labeled_terma["n_aspects"] == 1)
        &
        (labeled_terma["n_opinions"] == 1)
    ).sum()
)

print(
    "Multi aspect:",
    (
        labeled_terma["n_aspects"] > 1
    ).sum()
)

print(
    "Multi opinion:",
    (
        labeled_terma["n_opinions"] > 1
    ).sum()
)

print(
    "No aspect:",
    (
        labeled_terma["n_aspects"] == 0
    ).sum()
)

print(
    "No opinion:",
    (
        labeled_terma["n_opinions"] == 0
    ).sum()
)

Labeled sentences: 4000
1 aspect + 1 opinion: 696
Multi aspect: 1959
Multi opinion: 2769
No aspect: 695
No opinion: 260

In [14]:
# ============================================================
# FINAL CLEANUP TERMA
# ============================================================

terma["n_aspects"] = terma["n_aspects"].astype("Int64")
terma["n_opinions"] = terma["n_opinions"].astype("Int64")

terma.head()

,sentence_id,dataset,source_split,sentence,tokens,labels,aspects,opinions,n_aspects,n_opinions,labels_available
0,terma_train_00000,terma,train,kamar saya ada kendala di ac tidak berfungsi o...,"[""kamar"", ""saya"", ""ada"", ""kendala"", ""di"", ""ac""...","[""O"", ""O"", ""O"", ""O"", ""O"", ""B-ASPECT"", ""B-SENTI...","[{""start"": 5, ""end"": 5, ""text"": ""ac""}, {""start...","[{""start"": 6, ""end"": 8, ""text"": ""tidak berfung...",2,2,True
1,terma_train_00001,terma,train,tempatnya bagus . kolam renangnya bersih .,"[""tempatnya"", ""bagus"", ""."", ""kolam"", ""renangny...","[""B-ASPECT"", ""B-SENTIMENT"", ""O"", ""B-ASPECT"", ""...","[{""start"": 0, ""end"": 0, ""text"": ""tempatnya""}, ...","[{""start"": 1, ""end"": 1, ""text"": ""bagus""}, {""st...",2,2,True
2,terma_train_00002,terma,train,"oke banget , tetapi ac nya tidak bisa diatur s...","[""oke"", ""banget"", "","", ""tetapi"", ""ac"", ""nya"", ...","[""B-SENTIMENT"", ""I-SENTIMENT"", ""O"", ""O"", ""B-AS...","[{""start"": 4, ""end"": 5, ""text"": ""ac nya""}]","[{""start"": 0, ""end"": 1, ""text"": ""oke banget""},...",1,2,True
3,terma_train_00003,terma,train,pintu geser kurang rapat .,"[""pintu"", ""geser"", ""kurang"", ""rapat"", "".""]","[""B-ASPECT"", ""I-ASPECT"", ""B-SENTIMENT"", ""I-SEN...","[{""start"": 0, ""end"": 1, ""text"": ""pintu geser""}]","[{""start"": 2, ""end"": 3, ""text"": ""kurang rapat""}]",1,1,True
4,terma_train_00004,terma,train,keren . nyaman semuanya .,"[""keren"", ""."", ""nyaman"", ""semuanya"", "".""]","[""B-SENTIMENT"", ""O"", ""B-SENTIMENT"", ""B-ASPECT""...","[{""start"": 3, ""end"": 3, ""text"": ""semuanya""}]","[{""start"": 0, ""end"": 0, ""text"": ""keren""}, {""st...",1,2,True

In [15]:
PROCESSED = (
    ROOT / "data" / "processed"
)

PROCESSED.mkdir(
    parents=True,
    exist_ok=True
)

terma.to_csv(
    PROCESSED / "terma_processed.csv",
    index=False
)

In [20]:
terma_meta = terma[
    [
        "sentence_id",
        "dataset",
        "source_split",
        "labels_available",
        "n_aspects",
        "n_opinions",
    ]
].copy()

Processeing Hoasa Dataset

In [16]:
hoasa_raw = load_hoasa()

hoasa = prepare_hoasa(
    hoasa_raw
)

hoasa.head()

Using the latest cached version of the dataset since indonlp/indonlu couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'hoasa' at C:\Users\USER\.cache\huggingface\datasets\indonlp___indonlu\hoasa\1.0.0\4f6bd3985d38bfa901609cc151c052caaa4612322688a67e5aec267a78e930a0 (last modified on Fri Aug 21 00:08:35 2026).

,sentence_id,dataset,source_split,sentence,labels_available,ac,air_panas,bau,general,kebersihan,linen,service,sunrise_meal,tv,wifi
0,hoasa_train_00000,hoasa,train,kebersihan kurang...,True,neut,neut,neut,neut,neg,neut,neut,neut,neut,neut
1,hoasa_train_00001,hoasa,train,"sangat mengecewakan... hotel bad image, kebers...",True,neut,neut,neut,neut,neg,neut,neut,neut,neut,neut
2,hoasa_train_00002,hoasa,train,Tempat nyaman bersih tapi tv terlalu tinggi ti...,True,neut,neut,neut,neut,pos,neut,neut,neut,neg,neut
3,hoasa_train_00003,hoasa,train,"semuanya bagus sesuai profile,dan harga promo ...",True,neut,neg,neut,pos,neut,neut,neut,neut,neut,neut
4,hoasa_train_00004,hoasa,train,"Tempat tidur sangat keras, bantal besar dan ke...",True,neg,neg,neut,neut,neut,neg,neut,neut,neut,neut

In [17]:
hoasa.shape

(2854, 15)

In [18]:
hoasa[
    hoasa["source_split"] == "train"
].head(10)

,sentence_id,dataset,source_split,sentence,labels_available,ac,air_panas,bau,general,kebersihan,linen,service,sunrise_meal,tv,wifi
0,hoasa_train_00000,hoasa,train,kebersihan kurang...,True,neut,neut,neut,neut,neg,neut,neut,neut,neut,neut
1,hoasa_train_00001,hoasa,train,"sangat mengecewakan... hotel bad image, kebers...",True,neut,neut,neut,neut,neg,neut,neut,neut,neut,neut
2,hoasa_train_00002,hoasa,train,Tempat nyaman bersih tapi tv terlalu tinggi ti...,True,neut,neut,neut,neut,pos,neut,neut,neut,neg,neut
3,hoasa_train_00003,hoasa,train,"semuanya bagus sesuai profile,dan harga promo ...",True,neut,neg,neut,pos,neut,neut,neut,neut,neut,neut
4,hoasa_train_00004,hoasa,train,"Tempat tidur sangat keras, bantal besar dan ke...",True,neg,neg,neut,neut,neut,neg,neut,neut,neut,neut
5,hoasa_train_00005,hoasa,train,selimut dan handuk ada kerak kotor.,True,neut,neut,neut,neut,neut,neg,neut,neut,neut,neut
6,hoasa_train_00006,hoasa,train,"Kamar mandi perlu ditingkatkan lagi, showernya...",True,neut,neut,neut,neut,neg,neut,neut,neut,neut,neut
7,hoasa_train_00007,hoasa,train,Pelayanan minta sarapan lebih pagi tdk bisa ka...,True,neut,neut,neut,neut,neut,neut,neg,neut,neut,neut
8,hoasa_train_00008,hoasa,train,Kamar tidak sesuai dengan gambar...kurang bers...,True,neut,neut,neut,neut,neg,neg,neut,neut,neut,neut
9,hoasa_train_00009,hoasa,train,"AC tidak dingin, kunci kamar tidak bisa dipaka...",True,neg,neut,neut,neut,neut,neut,neut,neut,neut,neut

In [19]:
hoasa.to_csv(
    PROCESSED / "hoasa_processed.csv",
    index=False
)

In [21]:
hoasa_meta = hoasa[
    [
        "sentence_id",
        "dataset",
        "source_split",
        "labels_available",
    ]
].copy()

hoasa_meta["n_aspects"] = None
hoasa_meta["n_opinions"] = None

In [22]:
metadata = pd.concat(
    [
        terma_meta,
        hoasa_meta
    ],
    ignore_index=True
)

metadata.to_csv(
    PROCESSED
    / "sentence_metadata.csv",
    index=False
)